### ISSUE TITLE
projectM::renderFrame() synchronization

### ISSUE THREAD

**Issue by mbellew** [projectM-visualizer/projectm#147]
I think I tracked down another ghost.  If I leave projectM running it will crash after an hour (or four).  I believe this is due to bad synchronization in projectM::renderFrame().  Here's my reasoning:

It makes the following call to wake up the background thread to call projectM::evaluateSecondPreset()

`    pthread_cond_signal(&condition);`

At which point the background thread presumably will wake up and start running evaluateSecondPreset().  Later the foreground thread waits for the background thread to finish its work by making this call

`    pthread_mutex_lock( &mutex );`

That seems correct, because while the background thread is running, it holds the lock so the foreground thread will be forced to wait to acquire this lock.

I think there are two bugs here, let me know if I've got this right before I embarrass myself with a bad PR.

1) The foreground thread is assuming that the background thread will wake up in response to the pthread_cond_signal() _before_ the foreground thread can finish its work and get to its pthread_mutex_lock().  This seems to be true 999 times out of 1000.  But what if the background thread is really sleepy, and does not wake up for a long time.  It could still be asleep (even though it is eligible to wake up), and not have taken hold of the mutex yet.  Then the foreground thread will blow thorough its lock/unlock.  Then the background thread finally wakes up... and toes are gonna get stepped on.

2) My undestanding is that it's not best practice to assume the world is in the state you expect when a thread awakes from a pthread_cond_wait().  So it's probably a good idea to put use explicit state variable to communicate between the two threads that there is work to be done (or work is finished).

What finally tipped me of was seeing a stack trace with the background thread running evaluateSecondPreset(), and the main thread off doing something completely unrelated instead of being in renderFrame() like you'd expect.

Thread 9 
#4  0x000055ed3913b12c in projectM::evaluateSecondPreset (this=this@entry=0x55ed3aa66cb0) at projectM.cpp:321
#5  0x000055ed3913b1e2 in projectM::thread_func (this=0x55ed3aa66cb0, vptr_args=<optimized out>) at projectM.cpp:304
#6  0x000055ed3913b23c in thread_callback (prjm=<optimized out>) at projectM.cpp:287
#7  0x00007f75ce07f6db in start_thread (arg=0x7f759cba0700) at pthread_create.c:463
#8  0x00007f75cdda888f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 
#6  0x00007f75c23d88f2 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
#7  0x00007f75cf8ec00a in QOpenGLContext::swapBuffers(QSurface*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#8  0x00007f75cf31f5b5 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f75cf32c027 in QTimer::timeout(QTimer::QPrivateSignal) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007f75cf32c388 in QTimer::timerEvent(QTimerEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f75cf3200db in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007f75d006e82c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007f75d00760f4 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x000055ed3910ccbd in ProjectMApplication::notify (this=<optimized out>, receiver=<optimized out>, event=<optimized out>) at qprojectM-pulseaudio.cpp:101
#15 0x00007f75cf2f09a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007f75cf348d8e in QTimerInfoList::activateTimers() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007f75cf349589 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007f75cc39c387 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007f75cc39c5c0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007f75cc39c64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007f75cf3498ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007f75cf2ee9ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007f75cf2f7a84 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x000055ed39105a27 in main (argc=<optimized out>, argc@entry=1, argv=argv@entry=0x7fffa1d74b38) at qprojectM-pulseaudio.cpp:143
#25 0x00007f75cdca8b97 in __libc_start_main (main=0x55ed39105860 <main(int, char**)>, argc=1, argv=0x7fffa1d74b38, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffa1d74b28) at ../csu/libc-start.c:310
#26 0x000055ed3910c55a in _start ()

**Comment by revmischa** [comment]
I don't really know how this works now, but if execution should be serialized between the threads perhaps it should use a semaphore instead of a mutex? When the foreground thread should wait for background thread to finish its business before moving on, should foreground wait on a semaphore that is given by background when it finishes?

**Comment by mbellew** [comment]
The producer-consumer example at the bottom of this page shows the pattern (where queue size == 1)

https://docs.oracle.com/cd/E19455-01/806-5257/6je9h032r/index.html
