### ISSUE TITLE
Crash on start free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by TranarchySec** [projectM-visualizer/projectm#241]
It crashes on launch for me on Kubuntu 19 and latest Parrot OS. Is this perhaps a KDE issue
```

# projectM-pulseaudio 
dir:/usr/share/projectM/config.inp 
reading ~/.projectM/config.inp 
[projectM] config file: /root/.projectM/config.inp
No Textures Loaded from "/usr"/share/projectM/textures
[projectM] Allocating idle preset...
[PresetFactory] path is Geiss & Sperl - Feedback (projectM idle HDR mix).milk
[PresetFactory] url is idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
Connection failure: Connection refused
[PresetFactory] path is r/share/projectM/presets/CrystalHigh - mad ravetriping.milk
[PresetFactory] url is /usr/share/projectM/presets/CrystalHigh - mad ravetriping.milk
free(): double free detected in tcache 2
Aborted

```

**Comment by TranarchySec** [comment]
`(gdb) run
Starting program: /usr/bin/projectM-pulseaudio 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
dir:/usr/share/projectM/config.inp 
reading ~/.projectM/config.inp 
[New Thread 0x7ffff268f700 (LWP 14611)]
[New Thread 0x7ffff1dd5700 (LWP 14612)]
[New Thread 0x7ffff15d4700 (LWP 14613)]
[New Thread 0x7ffff0dd3700 (LWP 14614)]
[New Thread 0x7fffe3096700 (LWP 14615)]
[projectM] config file: /home/sysop/.projectM/config.inp
No Textures Loaded from "/usr"/share/projectM/textures
[projectM] Allocating idle preset...
[PresetFactory] path is Geiss & Sperl - Feedback (projectM idle HDR mix).milk
[PresetFactory] url is idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
[New Thread 0x7fffe0b31700 (LWP 14618)]
[New Thread 0x7fffd78f4700 (LWP 14619)]
[New Thread 0x7fffd70f3700 (LWP 14620)]
[Thread 0x7fffd78f4700 (LWP 14619) exited]
unconnected: connecting... 
connectHelper:  "alsa_output.pci-0000_00_1f.3.analog-stereo.monitor" 
CREATED 
READY 
[PresetFactory] path is r/share/projectM/presets/Rovastar - Eye On Reality (Mega 3 Mix)_phat_edit.milk
[PresetFactory] url is /usr/share/projectM/presets/Rovastar - Eye On Reality (Mega 3 Mix)_phat_edit.milk
free(): double free detected in tcache 2

Thread 1 "projectM-pulsea" received signal SIGABRT, Aborted.
0x00007ffff6943081 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff6943081 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff692e535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff6984db8 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff698b48a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff698ce4d in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007ffff7f6aa90 in ?? () from /lib/libprojectM-qt.so.1
#6  0x00007ffff7093bc0 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) ()
   from /lib/x86_64-linux-gnu/libQtCore.so.4
#7  0x00007ffff7f8f70d in QProjectM::presetSwitchedSignal(bool, unsigned int) const ()
   from /lib/libprojectM-qt.so.1
#8  0x00007ffff7ebfe52 in projectM::default_key_handler(projectMEvent, projectMKeycode) ()
   from /lib/libprojectM.so.2
#9  0x00007ffff7f906f9 in QProjectMWidget::keyReleaseEvent(QKeyEvent*) () from /lib/libprojectM-qt.so.1
#10 0x00007ffff7589928 in QWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQtGui.so.4
#11 0x00007ffff72301a3 in QGLWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQtOpenGL.so.4
#12 0x00007ffff75379bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /lib/x86_64-linux-gnu/libQtGui.so.4
#13 0x00007ffff753e5d6 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQtGui.so.4
#14 0x0000555555561bed in ProjectMApplication::notify(QObject*, QEvent*) ()
#15 0x00007ffff707f9fb in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /lib/x86_64-linux-gnu/libQtCore.so.4
#16 0x00007ffff75d476d in ?? () from /lib/x86_64-linux-gnu/libQtGui.so.4
#17 0x00007ffff75d4ae6 in ?? () from /lib/x86_64-linux-gnu/libQtGui.so.4
#18 0x00007ffff75af61f in QApplication::x11ProcessEvent(_XEvent*) () from /lib/x86_64-linux-gnu/libQtGui.so.4
#19 0x00007ffff75d6e5c in ?? () from /lib/x86_64-linux-gnu/libQtGui.so.4
#20 0x00007ffff648b9ee in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff648bc88 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#22 0x00007ffff648bd1c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff70ac861 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /lib/x86_64-linux-gnu/libQtCore.so.4
#24 0x00007ffff75d6fe7 in ?? () from /lib/x86_64-linux-gnu/libQtGui.so.4
#25 0x00007ffff707e28f in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /lib/x86_64-linux-gnu/libQtCore.so.4
#26 0x00007ffff707e55e in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /lib/x86_64-linux-gnu/libQtCore.so.4
#27 0x00007ffff7083a3a in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQtCore.so.4
#28 0x00005555555609f0 in main ()
`
